name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Buildozer Action
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          command: android debug
          buildozer_version: master

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Final
          path: bin/*.apk
