name: Build APK Final
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kivy/buildozer:master
    steps:
      - uses: actions/checkout@v4
      - name: Build com Buildozer
        run: |
          # Aceita licenças e inicia o build direto no container pronto
          buildozer -v android debug --accept-sdk-license
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK_Final
          path: bin/*.apk
          
